name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch, like 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Ruby environment (Jekyll is Ruby-based)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'

      # Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Build the Jekyll site
      - name: Build the site
        run: |
          bundle exec jekyll build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Arth2001/arth2001.github.io.git
            git push origin gh-pages